### ISSUE TITLE
直接git后运行报错，错误 ImportError: There is no such entity as cosyvoice.utils.common.ras_sampling

### ISSUE THREAD

**Issue by Wangmengguo** [v3ucn/CosyVoice_for_MacOs#5]
参照教程：https://www.cnblogs.com/v3ucn/p/18288786

使用设备：MacBook m1 air

完整报错：Traceback (most recent call last):
  File "webui.py", line 67, in <module>
    cosyvoice = CosyVoice(args.model_dir)
  File "/Users/arnoldwang/CosyVoice_for_MacOs/cosyvoice/cli/cosyvoice.py", line 46, in __init__
    configs = load_hyperpyyaml(f)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/cosyvoice/lib/python3.8/site-packages/hyperpyyaml/core.py", line 491, in _construct_name
    raise ImportError("There is no such entity as %s" % callable_string)
ImportError: There is no such entity as cosyvoice.utils.common.ras_sampling

**Comment by kamalkk** [comment]
相同的错误，有解决的吗

**Comment by CodeDestiny** [comment]
同样的问题，我是M1Pro

**Comment by johnninja** [comment]
同样的问题，我也是M1Pro
